/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import src.Account;

/**
 *
 * @author jpr70
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        
        Account account = new Account();

        final JPanel nePage = new NewExpense(account);
        final JPanel niPage = new NewIncome(account);
        final Menu menu = new Menu();

        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                JPanel panelTrocar = null;
                if ( e.getSource() == menu.newIncome ) {
                    panelTrocar = niPage;
                } else {
                    panelTrocar = nePage;
                }

                getContentPane().removeAll();

                getContentPane().add( panelTrocar );

                revalidate();
                repaint();
            }

        };

        setJMenuBar(menu.init(actionListener));

        add( niPage );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }
}
