/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import src.Account;

/**
 *
 * @author jpr70
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setTitle("BuyBeans");
        
        final Account account = new Account();
        final JPanel home = new NewIncome(account);
        final Menu menu = new Menu();

        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                JPanel panelTrocar = null;
                if ( e.getSource() == menu.newIncome ) {
                    panelTrocar = new NewIncome(account);
                } 
                if ( e.getSource() == menu.newExpense ){
                    panelTrocar = new NewExpense(account);
                } 
                if ( e.getSource() == menu.incomesList ){
                    panelTrocar = new Incomes(account);
                } 
                if ( e.getSource() == menu.expensesList ){
                    panelTrocar = new Expenses(account);
                }

                getContentPane().removeAll();

                getContentPane().add( panelTrocar );

                revalidate();
                repaint();
            }

        };

        setJMenuBar(menu.init(actionListener));
        add( home );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }
}
